**Question 1**

In [2]:
import numpy as np

In [4]:
arr = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])
arr

array([[ 2,  3,  5],
       [ 4,  6,  8],
       [11, 13, 17],
       [ 7, 10, 13]])

In [55]:
import numpy as np

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    else:
        return True

def contains_primes(arr):
    rows_with_primes = []
    for row in arr:
        for num in row:
            if is_prime(num):
                rows_with_primes.append(row)
                break  
    return np.array(rows_with_primes)

In [59]:
contains_primes(arr)

array([[ 2,  3,  5],
       [11, 13, 17],
       [ 7, 10, 13]])

***

**Question 2**

In [87]:
def checkerboard():
    list = []
    for i in range(64):
        list = np.append(list, 0)
    arr = np.array([list])
    board = arr.reshape(8, 8)
    return board

checkerboard()

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [167]:
def alternating_odd_checkerboard():
    arr = checkerboard()
    for i in range(len(arr)):
        if i % 2 == 0:
            for j in range(len(arr[i])):
                if j % 2 == 0:
                    arr[i, j] = 1
    return arr
alternating_checkerboard()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [173]:
def alternating_even_checkerboard():
    arr = alternating_odd_checkerboard()
    for i in range(len(arr)):
        if i % 2 != 0:
            for j in range(len(arr[i])):
                if j % 2 != 0:
                    arr[i, j] = 1
    return arr
alternating_even_checkerboard()

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [179]:
def reverse_checkerboard():
    arr = checkerboard()
    for i in range(len(arr)):
        if i % 2 == 0:
            for j in range(len(arr[i])):
                if j % 2 != 0:
                    arr[i, j] = 1
        elif i % 2 != 0:
            for j in range(len(arr[i])):
                if j % 2 == 0:
                    arr[i, j] = 1
    return arr

reverse_checkerboard()    

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

***

**Question 3**

In [267]:
universe = np.array(["galaxy", "clusters"])
def expansion(arr, spaces):
    expanded_words = []
    for word in arr:
        expanded_word = word[0]
        for i in range(1, len(word)):
            expanded_word = expanded_word + " " * spaces + word[i]  # Insert spaces before each next character
        expanded_words.append(expanded_word)
    return np.array(expanded_words)

In [269]:
expansion(universe, 1)

array(['g a l a x y', 'c l u s t e r s'], dtype='<U15')

***

**Question 4**

In [277]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
stars

array([[1889, 1906, 1846, 1622, 1541],
       [ 606, 1647, 1738,  596,  613],
       [1138,  547,  573, 1442,  724],
       [ 611, 1933, 1863, 1346, 1777],
       [ 920, 1108, 1732, 1592,  951]])

In [291]:
def secondDimmest(arr):
    sorted_arr = np.sort(arr, axis = 0)
    return sorted_arr[1]

In [293]:
secondDimmest(stars)

array([ 611, 1108, 1732, 1346,  724])